### ISSUE TITLE
关于网关的思考

### ISSUE THREAD

**Issue by witskeeper** [netcorepal/netcorepal-cloud-framework#3]
咱们设计这套组件，目的是在`扩展性/定制化能力`和`易用性`方面探索价值，基于这个考虑，我认为网关需要提供下列能力：

+ [ ] 开箱即用的部署方式
    + [ ] 提供Docker直接部署
    + [ ] 包引用方式的构建与部署模版
+ [ ] 提供Dashboard可视化管理能力
    + [ ] 配置管理
    + [ ] 路由管理
    + [ ] 运行状况展示
+ [ ] 内置能力
    + [ ] 服务路由
    + [ ] 身份认证
    + [ ] 上下文构造与传递能力
    + [ ] 灰度能力
    + [ ] 熔断限流能力
+ [ ] 扩展能力
    + [ ] Dashboard扩展
    + [ ] 路由能力扩展
    + [ ] 熔断限流能力扩展

**Comment by ZUOXIANGE** [comment]
.net领域应该没有一个类似[shenyu](https://github.com/apache/shenyu)这样的API网关

**Comment by witskeeper** [comment]
对于网关，我们推荐使用[YARP](https://github.com/microsoft/reverse-proxy)来根据自己的需求实现，开箱即用，非常便捷。
另外我们也基于YARP做了一个[IngressController](https://github.com/netcorepal/netcorepal-ingress-controller)的实例供大家参考
