### ISSUE TITLE
有关多租户

### ISSUE THREAD

**Issue by MingHuiJian** [netcorepal/netcorepal-cloud-framework#32]
看开发计划有多租户支持的，什么时候开始？

**Comment by witskeeper** [comment]
目前已支持租户上下文的传递，因此，可以理解为已经支持了多租户。
目前缺少的是全局ORM按租户数据隔离的过滤器，没有添加的原因是我们发现业务逻辑模块，还是得关注租户这个参数，得按需过滤数据。后续倒是可以考虑添加一个可选的过滤器。
同时也支持按租户的`灰度隔离`。
