### ISSUE TITLE
关于用DbContextDesignFactory做数据执行迁移命令

### ISSUE THREAD

**Issue by MingHuiJian** [netcorepal/netcorepal-cloud-framework#33]
因为我想将Migrations文件放到Infrastructure,所以使用IDesignTimeDbContextFactory接口
在new DbContextOptionsBuilder时因为框架的构造AppDbContextBase构造函数必须要有IMediator，使用数据库迁移命令总是报错
public class ApplicationDbContextDesignFactory : IDesignTimeDbContextFactory<XxxxDbContext>
{
    public XxxxDbContextCreateDbContext(string[] args)
    {
        IServiceCollection services = new ServiceCollection();
        var provider = services.BuildServiceProvider();
        services.AddMediatR(cfg => cfg.RegisterServicesFromAssemblies(Assembly.GetExecutingAssembly()));
        var mediator = provider.GetRequiredService<IMediator>();
        return new(new DbContextOptionsBuilder<XxxxDbContext>()
            .UseMySql("Server=********;User ID=mesuser;Password=**********;Port=3337;Database=Xxxx;CharSet=UTF8mb4;SslMode=none;AllowPublicKeyRetrieval=true",
                new MySqlServerVersion(new Version(8, 0, 32))).Options, mediator, provider);
    }
}

Unable to create a 'DbContext' of type ''. The exception 'No service for type 'MediatR.IMediator' has been registered.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

**Comment by witskeeper** [comment]
有StackTrace信息吗？

**Comment by witskeeper** [comment]
`XxxxDbContext` 的定义是否将参数传给`AppDbContextBase`

**Comment by MingHuiJian** [comment]
只是在包管理器执行迁移命令Add-Migration InitialCreate没有StackTrace信息

**Comment by MingHuiJian** [comment]
XxxxDbContext 将参赛数传给AppDbContextBase了的
public XxxxDbContext (DbContextOptions<RbacDbContext> options, IMediator mediator, IServiceProvider provider) : base(
    options, mediator, provider)
{
    Database.EnsureCreated();
}

**Comment by MingHuiJian** [comment]
是不是Infrastructure没有MediatR 处理程序注册服务注册不了

**Comment by witskeeper** [comment]
这两行代码顺序错了
```
var provider = services.BuildServiceProvider();
services.AddMediatR(cfg => cfg.RegisterServicesFromAssemblies(Assembly.GetExecutingAssembly()));、
```

你应该先 `AddMediatR` 再 `BuildServiceProvider`，改成下面这样应该就可以了：

```
services.AddMediatR(cfg => cfg.RegisterServicesFromAssemblies(Assembly.GetExecutingAssembly()));
var provider = services.BuildServiceProvider();
```

**Comment by MingHuiJian** [comment]
可以了，谢谢！
