### ISSUE TITLE
领域服务

### ISSUE THREAD

**Issue by zjzhaoy** [netcorepal/netcorepal-cloud-framework#4]
是不是还缺少领域服务的抽象设计？

**Comment by witskeeper** [comment]
这块目前是缺少的，你可以详细说说你的设计想法

**Comment by witskeeper** [comment]
一般而言，领域服务是用来处理两个或多个领域模型之间的相互作用的一种类型，而我们更倾向于通过事件驱动来达成此效果，尽量避免领域服务来耦合领域
