### ISSUE TITLE
添加领域事件转换为集成事件的转换器设计模式

### ISSUE THREAD

**Issue by witskeeper** [netcorepal/netcorepal-cloud-framework#52]
1. 添加领域事件转换为集成事件的转换器
2. 自动生成领域事件订阅和集成事件发布代码

可以获得好处：

1. 显式指示出集成事件的产生
2. 避免将集成事件发布的代码与其它业务代码混在一起

**Comment by santubeikawhi** [comment]
我可以尝试实现该功能
