### ISSUE TITLE
实体对象定义多个领域事件时，是否需要排序？

### ISSUE THREAD

**Issue by chenqilscy** [netcorepal/netcorepal-cloud-framework#57]
![image](https://github.com/user-attachments/assets/79c95c0d-2205-4000-abc5-bfaa94efbba5)

**Comment by witskeeper** [comment]
我的理解是无需排序，因为事件本身应该是相互独立无依赖的

**Comment by chenqilscy** [comment]
另外还有个相关的问题，集成事件的发送时机，应该在事务的外面还是内面？
我的理解是，集成事件，是一个异步事件，应该是发送机制里面需要保障它能成功发送，如果出错，也不能影响事务的提交

**Comment by witskeeper** [comment]
> 另外还有个相关的问题，集成事件的发送时机，应该在事务的外面还是内面？ 我的理解是，集成事件，是一个异步事件，应该是发送机制里面需要保障它能成功发送，如果出错，也不能影响事务的提交

是这样设计的，最新版本会提供一个设计点，可以参考文档 https://netcorepal.github.io/netcorepal-cloud-framework/domain/integration-converter/
