### ISSUE TITLE
如果不在领域事件中处理事务，那领域事件的一致性怎么保证么？

### ISSUE THREAD

**Issue by yc-2503** [netcorepal/netcorepal-cloud-framework#6]

**Comment by yc-2503** [comment]
> 领域事件（DomainEventHandler）的处理是和命令（CommandHandler）包在同一个数据库事务中的；
> 
> 集成事件的处理与`不在`同一个事务中

我主要是看到12月28号的那个commit中 把 DomainEventUnitOfWorkBehavior 给移除了，比较好奇，为什么要把这个事务处理给去掉。

**Comment by witskeeper** [comment]
逻辑上，`领域事件`由`领域模型`的变化触发，而`领域模型`的变化由`命令`控制
因此`领域事件`必定是在`命令`之内，目前没有必要为领域事件的处理器`DomainEventHandler`单独提供管理事务的能力。
所以就移除了`DomainEventUnitOfWorkBehavior`，实际上之前它也没有起作用。
