### ISSUE TITLE
模版项目 IntegrationEventHandler 执行过程报错 ，提示 EnvOptions.ServiceName is required

### ISSUE THREAD

**Issue by NewHeight** [netcorepal/netcorepal-cloud-framework#60]
![image](https://github.com/user-attachments/assets/300fde76-5304-493b-bf05-df1da2fbd076)

![image](https://github.com/user-attachments/assets/f749a411-d934-4a9a-ab2b-b63bf2e1a1cf)
![image](https://github.com/user-attachments/assets/91f7578c-2068-4c5d-94a6-0937a6d00fcb)

你好，我想问下根据文档创建的模版程序，在调用OrderController.SendEvent 发送集成事件后，IntegrationEventHandler 执行过程报错，提示 EnvOptions.ServiceName is required， 但是我看Program.cs 里没有配置EnvOptions 的地方，请问是需要额外配置吗？
@witskeeper

**Comment by witskeeper** [comment]
已经在https://github.com/netcorepal/netcorepal-cloud-template/issues/10 跟踪了
